export const authConstants = {
    INITIATE_AUTH: "INITIATE_AUTH",
    AUTH_ERROR: "AUTH_ERROR",
    CLEAR_AUTH_ERROR: "CLEAR_AUTH_ERROR",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

}