export const dairyMasterConstants = {
    GET_ALL_DAIRY_MASTER_REQUEST: "GET_ALL_DAIRY_MASTER_REQUEST",
    GET_ALL_DAIRY_MASTER_SUCCESS: "GET_ALL_DAIRY_MASTER_SUCCESS",
    GET_ALL_DAIRY_MASTER_ERROR: "GET_ALL_DAIRY_MASTER_ERROR",
    CLEAR_DAIRY_MASTER_ERROR: "CLEAR_DAIRY_MASTER_ERROR",

    ADD_DAIRY_MASTER_REQUEST: "ADD_DAIRY_MASTER_REQUEST",
    ADD_DAIRY_MASTER_SUCCESS: "ADD_DAIRY_MASTER_SUCCESS",
    ADD_DAIRY_MASTER_ERROR: "ADD_DAIRY_MASTER_ERROR",
    CLEAR_ADD_DAIRY_MASTER_ERROR: "CLEAR_ADD_DAIRY_MASTER_ERROR",

}